services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./problems:/app/problems
    environment:
      - PROBLEMS_DIR=/app/problems
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
